/**
 * game.service.ts — Core chess game business logic.
 *
 * Responsibilities:
 *   • Create new game records in the database with a starting FEN.
 *   • Validate and apply moves using chess.js (the authoritative chess engine).
 *   • Detect all game-over conditions: checkmate, stalemate, draw,
 *     threefold repetition, and insufficient material.
 *   • Persist updated board state (FEN, PGN, move history) after each move.
 *   • Handle game abandonment when a player disconnects or resigns.
 *
 * The server is the single source of truth — the client never mutates game
 * state directly; it only sends move requests and receives confirmations.
 */
import { Injectable } from '@nestjs/common';
import { Chess } from 'chess.js';
import { PrismaService } from '../prisma.service';
import { GameStatus, IMoveRequest, IMoveResponse } from '../common/interfaces/game.interface';

@Injectable()
export class GameService {
  constructor(private prisma: PrismaService) {}

  /**
   * Creates a new game between two players.
   * Initialises the board to the standard starting position and assigns
   * white the first turn. The game UUID is generated by PostgreSQL.
   */
  async createGame(whitePlayerId: string, blackPlayerId: string): Promise<any> {
    const chess = new Chess();

    const game = await this.prisma.game.create({
      data: {
        whitePlayerId,
        blackPlayerId,
        currentTurn: whitePlayerId, // White always moves first
        fen: chess.fen(),
        pgn: '',
        status: GameStatus.IN_PROGRESS,
        moveHistory: [],
      },
    });

    return game;
  }

  /** Fetches a game by its UUID, or returns null if not found. */
  async getGame(gameId: string): Promise<any> {
    return this.prisma.game.findUnique({
      where: { id: gameId },
    });
  }

  /**
   * Validates and applies a move for the given player.
   *
   * Validation steps:
   *   1. Game must exist and be IN_PROGRESS.
   *   2. It must be this player's turn (currentTurn === playerId).
   *   3. chess.js must accept the move as legal.
   *
   * After a valid move the function:
   *   • Updates FEN, PGN, currentTurn, and moveHistory in the DB.
   *   • Detects whether the game has ended and records winner / endReason.
   *
   * Returns an IMoveResponse describing the outcome.
   */
  async makeMove(
    gameId: string,
    playerId: string,
    moveRequest: IMoveRequest,
  ): Promise<IMoveResponse> {
    const game = await this.getGame(gameId);

    if (!game) {
      return { success: false, error: 'Game not found' };
    }

    if (game.status !== GameStatus.IN_PROGRESS) {
      return { success: false, error: 'Game is not in progress' };
    }

    if (game.currentTurn !== playerId) {
      return { success: false, error: 'Not your turn' };
    }

    // Load the current board position from the stored FEN string
    const chess = new Chess(game.fen);

    try {
      // chess.move() returns null for illegal moves and throws for malformed input
      const move = chess.move({
        from: moveRequest.from,
        to: moveRequest.to,
        promotion: moveRequest.promotion || 'q', // Default to queen promotion
      });

      if (!move) {
        return { success: false, error: 'Illegal move' };
      }

      // Determine whose turn it is next
      const nextTurn =
        game.currentTurn === game.whitePlayerId
          ? game.blackPlayerId
          : game.whitePlayerId;

      // Check all possible game-over conditions
      const isGameOver = chess.isGameOver();
      let winner: string | undefined;
      let endReason: string | undefined;

      if (isGameOver) {
        if (chess.isCheckmate()) {
          winner = playerId;       // The player who just moved wins
          endReason = 'checkmate';
        } else if (chess.isStalemate()) {
          endReason = 'stalemate';
        } else if (chess.isThreefoldRepetition()) {
          endReason = 'threefold_repetition';
        } else if (chess.isInsufficientMaterial()) {
          endReason = 'insufficient_material';
        } else if (chess.isDraw()) {
          endReason = 'draw';
        }
      }

      // Persist the updated game state
      await this.prisma.game.update({
        where: { id: gameId },
        data: {
          fen: chess.fen(),
          pgn: chess.pgn(),
          currentTurn: nextTurn,
          status: isGameOver ? GameStatus.COMPLETED : GameStatus.IN_PROGRESS,
          winner,
          endReason,
          moveHistory: {
            push: `${moveRequest.from}-${moveRequest.to}`,
          },
        },
      });

      return {
        success: true,
        fen: chess.fen(),
        pgn: chess.pgn(),
        move: `${moveRequest.from}-${moveRequest.to}`,
        isGameOver,
        winner,
        endReason,
      };
    } catch (error) {
      return { success: false, error: 'Invalid move' };
    }
  }

  /** Hard-deletes a game record. Used in cleanup/test scenarios. */
  async deleteGame(gameId: string): Promise<void> {
    await this.prisma.game.delete({
      where: { id: gameId },
    });
  }

  /**
   * Finds the active (IN_PROGRESS) game for a given player, if any.
   * Used on reconnection to resume the player's ongoing game.
   */
  async findActiveGameByPlayer(playerId: string): Promise<any> {
    return this.prisma.game.findFirst({
      where: {
        OR: [
          { whitePlayerId: playerId },
          { blackPlayerId: playerId },
        ],
        status: GameStatus.IN_PROGRESS,
      },
    });
  }

  /**
   * Marks a game as COMPLETED with the abandoning player as the loser.
   * Called when a player disconnects or explicitly resigns.
   */
  async abandonGame(gameId: string, playerId: string): Promise<void> {
    const game = await this.getGame(gameId);
    if (!game) return;

    // The player who did NOT abandon is the winner
    const winner =
      game.whitePlayerId === playerId
        ? game.blackPlayerId
        : game.whitePlayerId;

    await this.prisma.game.update({
      where: { id: gameId },
      data: {
        status: GameStatus.COMPLETED,
        winner,
        endReason: 'opponent_left',
      },
    });
  }
}
